# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'mainwindow.ui'
#
# Created: Sun Feb 15 01:12:45 2015
#      by: PyQt5 UI code generator 5.4
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1323, 713)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.groupBox = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox.setGeometry(QtCore.QRect(340, 40, 286, 461))
        self.groupBox.setObjectName("groupBox")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.groupBox)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.graphicsView_card = QtWidgets.QGraphicsView(self.groupBox)
        self.graphicsView_card.setObjectName("graphicsView_card")
        self.verticalLayout_2.addWidget(self.graphicsView_card)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.pushButton_prev = QtWidgets.QPushButton(self.groupBox)
        self.pushButton_prev.setObjectName("pushButton_prev")
        self.horizontalLayout_2.addWidget(self.pushButton_prev)
        self.pushButton_next = QtWidgets.QPushButton(self.groupBox)
        self.pushButton_next.setObjectName("pushButton_next")
        self.horizontalLayout_2.addWidget(self.pushButton_next)
        self.verticalLayout_2.addLayout(self.horizontalLayout_2)
        self.pushButton_2 = QtWidgets.QPushButton(self.groupBox)
        self.pushButton_2.setObjectName("pushButton_2")
        self.verticalLayout_2.addWidget(self.pushButton_2)
        self.groupBox_3 = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox_3.setGeometry(QtCore.QRect(70, 540, 590, 127))
        self.groupBox_3.setObjectName("groupBox_3")
        self.gridLayout = QtWidgets.QGridLayout(self.groupBox_3)
        self.gridLayout.setObjectName("gridLayout")
        self.textEdit = QtWidgets.QTextEdit(self.groupBox_3)
        self.textEdit.setObjectName("textEdit")
        self.gridLayout.addWidget(self.textEdit, 0, 0, 1, 1)
        self.groupBox_2 = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox_2.setGeometry(QtCore.QRect(650, 60, 286, 275))
        self.groupBox_2.setObjectName("groupBox_2")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.groupBox_2)
        self.verticalLayout.setObjectName("verticalLayout")
        self.graphicsView_mana = QtWidgets.QGraphicsView(self.groupBox_2)
        self.graphicsView_mana.setObjectName("graphicsView_mana")
        self.verticalLayout.addWidget(self.graphicsView_mana)
        self.pushButton = QtWidgets.QPushButton(self.groupBox_2)
        self.pushButton.setObjectName("pushButton")
        self.verticalLayout.addWidget(self.pushButton)
        self.groupBox_base = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox_base.setGeometry(QtCore.QRect(20, 20, 281, 501))
        self.groupBox_base.setObjectName("groupBox_base")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.groupBox_base)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.listView_base = QtWidgets.QListView(self.groupBox_base)
        self.listView_base.setObjectName("listView_base")
        self.verticalLayout_3.addWidget(self.listView_base)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.label_type_base = QtWidgets.QLabel(self.groupBox_base)
        self.label_type_base.setObjectName("label_type_base")
        self.horizontalLayout_4.addWidget(self.label_type_base)
        self.comboBox_type_base = QtWidgets.QComboBox(self.groupBox_base)
        self.comboBox_type_base.setObjectName("comboBox_type_base")
        self.comboBox_type_base.addItem("")
        self.comboBox_type_base.addItem("")
        self.comboBox_type_base.addItem("")
        self.comboBox_type_base.addItem("")
        self.comboBox_type_base.addItem("")
        self.comboBox_type_base.addItem("")
        self.comboBox_type_base.addItem("")
        self.comboBox_type_base.addItem("")
        self.horizontalLayout_4.addWidget(self.comboBox_type_base)
        self.verticalLayout_3.addLayout(self.horizontalLayout_4)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.checkBox_r_base = QtWidgets.QCheckBox(self.groupBox_base)
        self.checkBox_r_base.setStyleSheet("background-color:rgb(128, 0, 0)")
        self.checkBox_r_base.setText("")
        self.checkBox_r_base.setChecked(True)
        self.checkBox_r_base.setObjectName("checkBox_r_base")
        self.horizontalLayout.addWidget(self.checkBox_r_base)
        self.checkBox_g_base = QtWidgets.QCheckBox(self.groupBox_base)
        self.checkBox_g_base.setStyleSheet("background-color:rgb(0, 128, 0)")
        self.checkBox_g_base.setText("")
        self.checkBox_g_base.setChecked(True)
        self.checkBox_g_base.setObjectName("checkBox_g_base")
        self.horizontalLayout.addWidget(self.checkBox_g_base)
        self.checkBox_w_base = QtWidgets.QCheckBox(self.groupBox_base)
        self.checkBox_w_base.setStyleSheet("background-color:rgb(255, 255, 255)")
        self.checkBox_w_base.setText("")
        self.checkBox_w_base.setChecked(True)
        self.checkBox_w_base.setObjectName("checkBox_w_base")
        self.horizontalLayout.addWidget(self.checkBox_w_base)
        self.checkBox_u_base = QtWidgets.QCheckBox(self.groupBox_base)
        self.checkBox_u_base.setStyleSheet("background-color:rgb(0, 0, 255)")
        self.checkBox_u_base.setText("")
        self.checkBox_u_base.setChecked(True)
        self.checkBox_u_base.setObjectName("checkBox_u_base")
        self.horizontalLayout.addWidget(self.checkBox_u_base)
        self.checkBox_b_base = QtWidgets.QCheckBox(self.groupBox_base)
        self.checkBox_b_base.setStyleSheet("background-color:rgb(0, 0, 0)")
        self.checkBox_b_base.setText("")
        self.checkBox_b_base.setChecked(True)
        self.checkBox_b_base.setObjectName("checkBox_b_base")
        self.horizontalLayout.addWidget(self.checkBox_b_base)
        self.verticalLayout_3.addLayout(self.horizontalLayout)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.labe_mana_base = QtWidgets.QLabel(self.groupBox_base)
        self.labe_mana_base.setObjectName("labe_mana_base")
        self.horizontalLayout_3.addWidget(self.labe_mana_base)
        self.comboBox_mana_base = QtWidgets.QComboBox(self.groupBox_base)
        self.comboBox_mana_base.setObjectName("comboBox_mana_base")
        self.comboBox_mana_base.addItem("")
        self.comboBox_mana_base.addItem("")
        self.comboBox_mana_base.addItem("")
        self.comboBox_mana_base.addItem("")
        self.comboBox_mana_base.addItem("")
        self.horizontalLayout_3.addWidget(self.comboBox_mana_base)
        self.spinBox_mana_base = QtWidgets.QSpinBox(self.groupBox_base)
        self.spinBox_mana_base.setMinimum(1)
        self.spinBox_mana_base.setMaximum(50)
        self.spinBox_mana_base.setProperty("value", 1)
        self.spinBox_mana_base.setObjectName("spinBox_mana_base")
        self.horizontalLayout_3.addWidget(self.spinBox_mana_base)
        self.verticalLayout_3.addLayout(self.horizontalLayout_3)
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.label = QtWidgets.QLabel(self.groupBox_base)
        self.label.setObjectName("label")
        self.horizontalLayout_5.addWidget(self.label)
        self.comboBox = QtWidgets.QComboBox(self.groupBox_base)
        self.comboBox.setObjectName("comboBox")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.horizontalLayout_5.addWidget(self.comboBox)
        self.verticalLayout_3.addLayout(self.horizontalLayout_5)
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1323, 22))
        self.menubar.setObjectName("menubar")
        self.menuDeck = QtWidgets.QMenu(self.menubar)
        self.menuDeck.setObjectName("menuDeck")
        self.menuCard = QtWidgets.QMenu(self.menubar)
        self.menuCard.setObjectName("menuCard")
        MainWindow.setMenuBar(self.menubar)
        self.actionLoad_data_base = QtWidgets.QAction(MainWindow)
        self.actionLoad_data_base.setObjectName("actionLoad_data_base")
        self.actionExit = QtWidgets.QAction(MainWindow)
        self.actionExit.setObjectName("actionExit")
        self.actionLoad_Deck = QtWidgets.QAction(MainWindow)
        self.actionLoad_Deck.setObjectName("actionLoad_Deck")
        self.actionSave_Deck = QtWidgets.QAction(MainWindow)
        self.actionSave_Deck.setObjectName("actionSave_Deck")
        self.actionDownload_images = QtWidgets.QAction(MainWindow)
        self.actionDownload_images.setObjectName("actionDownload_images")
        self.actionPrint_URL = QtWidgets.QAction(MainWindow)
        self.actionPrint_URL.setObjectName("actionPrint_URL")
        self.actionManaRlize = QtWidgets.QAction(MainWindow)
        self.actionManaRlize.setObjectName("actionManaRlize")
        self.actionGet_Statistics = QtWidgets.QAction(MainWindow)
        self.actionGet_Statistics.setObjectName("actionGet_Statistics")
        self.actionUpdate_Mana_Curve = QtWidgets.QAction(MainWindow)
        self.actionUpdate_Mana_Curve.setObjectName("actionUpdate_Mana_Curve")
        self.actionExit_2 = QtWidgets.QAction(MainWindow)
        self.actionExit_2.setObjectName("actionExit_2")
        self.actionPrint_JSON = QtWidgets.QAction(MainWindow)
        self.actionPrint_JSON.setObjectName("actionPrint_JSON")
        self.actionNext_Card_in_Deck = QtWidgets.QAction(MainWindow)
        self.actionNext_Card_in_Deck.setObjectName("actionNext_Card_in_Deck")
        self.actionPrev_Card_in_Deck = QtWidgets.QAction(MainWindow)
        self.actionPrev_Card_in_Deck.setObjectName("actionPrev_Card_in_Deck")
        self.actionDownload_Images = QtWidgets.QAction(MainWindow)
        self.actionDownload_Images.setObjectName("actionDownload_Images")
        self.menuDeck.addAction(self.actionLoad_Deck)
        self.menuDeck.addAction(self.actionSave_Deck)
        self.menuDeck.addSeparator()
        self.menuDeck.addAction(self.actionDownload_Images)
        self.menuDeck.addSeparator()
        self.menuDeck.addAction(self.actionManaRlize)
        self.menuDeck.addAction(self.actionUpdate_Mana_Curve)
        self.menuDeck.addAction(self.actionGet_Statistics)
        self.menuCard.addAction(self.actionPrint_URL)
        self.menuCard.addAction(self.actionPrint_JSON)
        self.menuCard.addSeparator()
        self.menuCard.addAction(self.actionNext_Card_in_Deck)
        self.menuCard.addAction(self.actionPrev_Card_in_Deck)
        self.menubar.addAction(self.menuDeck.menuAction())
        self.menubar.addAction(self.menuCard.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "ManaR"))
        self.groupBox.setTitle(_translate("MainWindow", "Card view"))
        self.pushButton_prev.setText(_translate("MainWindow", "<--"))
        self.pushButton_next.setText(_translate("MainWindow", "-->"))
        self.pushButton_2.setText(_translate("MainWindow", "ManaRlize"))
        self.groupBox_3.setTitle(_translate("MainWindow", "Deck Statistics"))
        self.groupBox_2.setTitle(_translate("MainWindow", "Mana Curve"))
        self.pushButton.setText(_translate("MainWindow", "Update"))
        self.groupBox_base.setTitle(_translate("MainWindow", "Base Deck"))
        self.label_type_base.setText(_translate("MainWindow", "Type"))
        self.comboBox_type_base.setItemText(0, _translate("MainWindow", "All Cards"))
        self.comboBox_type_base.setItemText(1, _translate("MainWindow", "Artifact"))
        self.comboBox_type_base.setItemText(2, _translate("MainWindow", "Creature"))
        self.comboBox_type_base.setItemText(3, _translate("MainWindow", "Enchantment"))
        self.comboBox_type_base.setItemText(4, _translate("MainWindow", "Instant"))
        self.comboBox_type_base.setItemText(5, _translate("MainWindow", "Land"))
        self.comboBox_type_base.setItemText(6, _translate("MainWindow", "Planeswalker"))
        self.comboBox_type_base.setItemText(7, _translate("MainWindow", "Sorcery"))
        self.labe_mana_base.setText(_translate("MainWindow", "Mana Cost"))
        self.comboBox_mana_base.setItemText(0, _translate("MainWindow", ">="))
        self.comboBox_mana_base.setItemText(1, _translate("MainWindow", "="))
        self.comboBox_mana_base.setItemText(2, _translate("MainWindow", "<"))
        self.comboBox_mana_base.setItemText(3, _translate("MainWindow", "<="))
        self.comboBox_mana_base.setItemText(4, _translate("MainWindow", ">"))
        self.label.setText(_translate("MainWindow", "Ability"))
        self.comboBox.setItemText(0, _translate("MainWindow", "Any"))
        self.comboBox.setItemText(1, _translate("MainWindow", "Dearthtouch"))
        self.comboBox.setItemText(2, _translate("MainWindow", "Flash"))
        self.comboBox.setItemText(3, _translate("MainWindow", "Flying"))
        self.comboBox.setItemText(4, _translate("MainWindow", "Haste"))
        self.comboBox.setItemText(5, _translate("MainWindow", "Hexproof"))
        self.comboBox.setItemText(6, _translate("MainWindow", "Indestructible"))
        self.comboBox.setItemText(7, _translate("MainWindow", "Lifelink"))
        self.comboBox.setItemText(8, _translate("MainWindow", "Morph"))
        self.comboBox.setItemText(9, _translate("MainWindow", "Outlast"))
        self.comboBox.setItemText(10, _translate("MainWindow", "Protection"))
        self.comboBox.setItemText(11, _translate("MainWindow", "Reach"))
        self.comboBox.setItemText(12, _translate("MainWindow", "Vigilance"))
        self.menuDeck.setTitle(_translate("MainWindow", "Deck"))
        self.menuCard.setTitle(_translate("MainWindow", "Card"))
        self.actionLoad_data_base.setText(_translate("MainWindow", "Load data base"))
        self.actionExit.setText(_translate("MainWindow", "Exit"))
        self.actionLoad_Deck.setText(_translate("MainWindow", "Load Deck"))
        self.actionSave_Deck.setText(_translate("MainWindow", "Save Deck"))
        self.actionDownload_images.setText(_translate("MainWindow", "Download images"))
        self.actionPrint_URL.setText(_translate("MainWindow", "Print URL"))
        self.actionManaRlize.setText(_translate("MainWindow", "ManaRlize"))
        self.actionGet_Statistics.setText(_translate("MainWindow", "Get Statistics"))
        self.actionUpdate_Mana_Curve.setText(_translate("MainWindow", "Update Mana Curve"))
        self.actionExit_2.setText(_translate("MainWindow", "Exit"))
        self.actionPrint_JSON.setText(_translate("MainWindow", "Print JSON"))
        self.actionNext_Card_in_Deck.setText(_translate("MainWindow", "Next Card in Deck"))
        self.actionPrev_Card_in_Deck.setText(_translate("MainWindow", "Prev Card in Deck"))
        self.actionDownload_Images.setText(_translate("MainWindow", "Download Images"))

